### ISSUE TITLE
PTemcee adjustable scale parameter (a)

### ISSUE THREAD

**Issue by suvenduat** [dfm/emcee#147]
Hi,
I am using Parallel tempering emcee. It seems that my problem is multimodal and the modes are widely  separated with low probability valleys. The mean acceptance fraction is ~0.1. I am adjusting 'a' down to ~1.25, which increases the acceptance fraction to ~0.14 and the results are quiet good, but I can never get mean acceptance fraction >0.2 since 'a' should not be <=1!! Right? Is there any way to increase the acceptance fraction or any way to deal with this kind of problem? Thanks!

**Comment by suvenduat** [comment]
Any suggestion?

**Comment by willvousden** [comment]
I guess this is a bit late, but for the benefit of anyone else looking at this:

The important thing here is to select your temperatures properly (rather than varying the scale parameter).  That's not easy, unfortunately, but you could try increasing the number of temperatures and/or decreasing their spacing.  You need to keep an eye on the *inter-chain* acceptance fraction here, as well as the *intra-chain* fraction.
