### ISSUE TITLE
Using multiprocess instead of multiprocessing

### ISSUE THREAD

**Issue by adwasser** [dfm/emcee#193]
I'd like to pass in bound methods to the `EnsembleSampler` for my log posterior function.  Python's default serialization module, `pickle`, makes that somewhat frustrating.  My current solution is just to replace `multiprocessing` with the `multiprocess` [module](https://pypi.python.org/pypi/multiprocess) whenever possible, e.g., adwasser/emcee@ea0948a6a2cdcb57e19ab123b321c5f0163faf00

Any thoughts on the feasibility of this as a workaround?  It get done what I need it to, but I'm not sure where it will break things.

Thanks!
Asher

**Comment by dfm** [comment]
You can just pass a `multiprocess.Pool` object to the [`EnsembleSampler` init](http://dan.iel.fm/emcee/current/api/#emcee.EnsembleSampler) using the `pool` keyword argument instead of actually editing the emcee source code.

There's nothing specifically wrong with what you're doing but it would require less of a hack than your current solution!
