### ISSUE TITLE
Discrepancy between line example on webpage and code example.

### ISSUE THREAD

**Issue by andyfaff** [dfm/emcee#217]
The [line example](http://dan.iel.fm/emcee/current/user/line/) is based on the code in
https://github.com/dfm/emcee/blob/master/examples/line.py. On [line 73[(https://github.com/dfm/emcee/blob/master/examples/line.py#L73) `chi2` is multiplied by a factor of 2. This factor of two is missing on the webpage `nll = lambda *args: -lnlike(*args)`.
Whilst I think the former makes more sense from considering the log-likelihood equation, when I examine `hess_inv` from the `minimize` output with the factor of two missing, then the covariance matrix matches that obtained from the sampling. If the factor of two is present, then `hess_inv` is ~twice as large as that obtained from the sampling.

**Comment by andyfaff** [comment]
Here is the code to reproduce:

	from __future__ import print_function

	import emcee
	import numpy as np
	import scipy.optimize as op

	# Reproducible results!
	np.random.seed(123)

	# Choose the "true" parameters.
	m_true = -0.9594
	b_true = 4.294
	f_true = 0.534

	# Generate some synthetic data from the model.
	N = 50
	x = np.sort(10*np.random.rand(N))
	yerr = 0.1+0.5*np.random.rand(N)
	y = m_true*x+b_true
	y += np.abs(f_true*y) * np.random.randn(N)
	y += yerr * np.random.randn(N)

	# Define the probability function as likelihood * prior.
	def lnprior(theta):
		m, b, lnf = theta
		if -5.0 < m < 0.5 and 0.0 < b < 10.0 and -10.0 < lnf < 1.0:
			return 0.0
		return -np.inf

	def lnlike(theta, x, y, yerr):
		m, b, lnf = theta
		model = m * x + b
		inv_sigma2 = 1.0/(yerr**2 + model**2*np.exp(2*lnf))
		return -0.5*(np.sum((y-model)**2*inv_sigma2 - np.log(inv_sigma2)))

	def lnprob(theta, x, y, yerr):
		lp = lnprior(theta)
		if not np.isfinite(lp):
			return -np.inf
		return lp + lnlike(theta, x, y, yerr)

	# Find the maximum likelihood value.
	chi2 = lambda *args: -2 * lnlike(*args)
	result = op.minimize(chi2, [m_true, b_true, np.log(f_true)], args=(x, y, yerr))
	print('hess_inv\n', result['hess_inv'])

	# Set up the sampler.
	ndim, nwalkers = 3, 100
	pos = [result["x"] + 1e-4*np.random.randn(ndim) for i in range(nwalkers)]
	sampler = emcee.EnsembleSampler(nwalkers, ndim, lnprob, args=(x, y, yerr))

	# Clear and run the production chain.
	sampler.run_mcmc(pos, 500, rstate0=np.random.get_state())

	burnin = 50
	samples = sampler.chain[:, burnin:, :].reshape((-1, ndim))
	samples[:, 2] = np.exp(samples[:, 2])
	covar = np.cov(samples.T)
	print('sampling covariance\n', covar)

and the output:

```
hess_inv
 [[ 0.00303107 -0.0136809   0.00315329]
 [-0.0136809   0.06330464 -0.01442403]
 [ 0.00315329 -0.01442403  0.01201837]]
sampling covariance
 [[ 0.00601421 -0.02713522  0.00284316]
 [-0.02713522  0.12575339 -0.01306871]
 [ 0.00284316 -0.01306871  0.0055466 ]]
```

if the factor of two is removed in the `chi2` lambda function then the covariance matrices match.

**Comment by dfm** [comment]
It's really just a question of definitions. In the case of fixed independent Gaussian uncertainties, the log-likelihood is (up to a constant) `ln(L) = -chi^2/2`. So `nll` refers to the negative log-likelihood and `chi` refers to `-2*ln(L)`. The "best-fit" parameters will be the same for `chi2` and for `nll` the way that I've defined them, but using `chi2` in this case is a bit sloppy because it includes the sigma penalty from the likelihood normalization – something that wouldn't normally be included in chi squared.

In this example, the posterior is not Gaussian so you shouldn't take the inverse Hessian too seriously, but if you do want a quick estimate of the curvature of the *likelihood function* then you should use `nll` (as you discovered).

Hope that helps!
