### ISSUE TITLE
Is the integrated autocorrelation time off by a factor 2?

### ISSUE THREAD

**Issue by lciti** [dfm/emcee#267]
**General information:**

- emcee version: 06aa307 (current)

**Problem description:**
According to eq 3.16 of [Sokal's document](http://www.stat.unc.edu/faculty/cji/Sokal.pdf), which is given as reference in `emcee/emcee/autocorr.py`, the integrated autocorrelation time should be computed as:
![\tau = \frac12 \sum_{t=-M}^{M} \hat\rho(t)](https://user-images.githubusercontent.com/14928209/43616120-de56cdec-96b2-11e8-8d99-9d1fc23f474a.png)

Unless I am missing something, owing to the symmetry of ρ(t), one can code this expression as:
`taus = np.cumsum(f) - 0.5`
while the current implementation is: 
`taus = 2.0*np.cumsum(f) - 1.0`.

**Comment by dfm** [comment]
It's just a choice of definition. I prefer to define tau as "the number of steps per independent sample" instead of defining 2*tau as that. If you read through Sokal a little more closely, you'll see that he discusses this factor of two as well. More notes can be found [here](http://emcee.readthedocs.io/en/latest/tutorials/autocorr/).

**Comment by mauro3** [comment]
To me, the docs (https://emcee.readthedocs.io/en/latest/tutorials/autocorr/#computing-autocorrelation-times, last equation of the section) suggest that it should be `taus = 2.0*np.cumsum(f) + 1.0`.
