### ISSUE TITLE
Pickling EnsembleSampler throws PicklingError on attribute log_prob_fn

### ISSUE THREAD

**Issue by benmaier** [dfm/emcee#368]
**General information:**

- Python version: 3.8.6
- emcee version: '3.0.3.dev35+g142797c'
- platform: darwin 
- installation method (pip/conda/source/other?): pip

**Problem description:**

Pickling an EnsembleSample throws the following error:

```
PicklingError: Can't pickle <function <lambda> at 0x152e4e1f0>: attribute lookup <lambda> on __main__ failed
```

### Expected behavior:

Pickles the `log_prob_fn` method.

### Actual behavior:

Throws PicklingError

### What have you tried so far?:

Setting 

```python
a.log_prob_fn = None
```
before pickling lets Python pickle the sampler

### Minimal example:

```python
import emcee
import pickle

a = emcee.EnsembleSampler(100,3,lambda x: x)
with open('.test.p','wb') as f:
    pickle.dump(a,f)
```

**Comment by benmaier** [comment]
Setting 

```python
a.log_prob_fn = None
```
before pickling lets Python pickle the sampler

**Comment by dfm** [comment]
@benmaier: Thanks!

This is as expected - methods defined in `main` will never be picklable! It's also worth noting that `pickle.dumps(lambda x: x)` also fails because lambda functions are not picklable.

The following does work:

```python
with open("demo.py", "w") as f:
    f.write("""
import numpy as np

def logprobfn(x):
    return -0.5 * np.sum(x**2)
""")
    
import emcee
import pickle
from demo import logprobfn

a = emcee.EnsembleSampler(100,3,logprobfn)
with open('.test.p','wb') as f:
    pickle.dump(a,f)
```

So if your probability function is defined in a module then you're good to go.

Your proposed solution is unfortunately not a good one since the sampler won't work after it's unpickled!

**My question for you**: Why do you want to pickle your sampler? Do you want to save the chain? Use the backends feature: https://emcee.readthedocs.io/en/stable/user/backends/

**Comment by benmaier** [comment]
this is an incredibly helpful response on so many levels :) thank you so much!
