### ISSUE TITLE
emcee.EnsembleSampler.sample with infinite iterations

### ISSUE THREAD

**Issue by carlosgmartin** [dfm/emcee#369]
**General information:**

- emcee version: 3.0.2
- platform: Python 3.8.5
- installation method (pip/conda/source/other?): `conda install -c conda-forge emcee`

**Problem description:**

It would be nice to be able to use [`emcee.EnsembleSampler.sample`](https://emcee.readthedocs.io/en/stable/user/sampler/#emcee.EnsembleSampler.sample) with infinite `iterations`, producing an unending stream of samples. This frees the caller from having to specify the number of iterations ahead of time, and allows them to take as many samples as they need *post facto*. I find myself using this pattern often, so I think it would be good from a UI standpoint.

**Comment by dfm** [comment]
This was possible in previous versions of emcee, but while I agree that it's elegant in theory, no one ever actually interfaced with the code that way and it's not such a good idea with the current version because of how the chains are stored. I tested an implementation where the backend memory wasn't pre-allocated and there was a huge computational overhead every time you need to resize the array. All that to say: if you *actually* want an infinite sampler, you should figure out what block size works for your problem and then put the `sampler.sample` calls (with that number of iterations) inside a `while True`. It's easy to restart where you left off (just pass an initial state of `None`). 

Take a look at this tutorial that gives a few examples the would be building blocks: https://emcee.readthedocs.io/en/stable/tutorials/monitor/

**Comment by carlosgmartin** [comment]
@dfm Does this apply with `store=False`?

**Comment by dfm** [comment]
You won't get any resizing overhead when `store=False`, true, but what's your use case where you want to run an infinite number of steps without saving them anywhere? And why is infinity better than a large integer? The default is `store=True` because, in my experience, that's how most people use the sampler, but I'm interested to understand why you think that something else would be a better UI!

**Comment by carlosgmartin** [comment]
It's a bit hard to explain, but I'm estimating something of the form f(E<sub>X ~ p</sub> g(X)) by using emcee to take samples from p, and eventually stopping the process once a certain condition on h(E<sub>X ~ p</sub> i(X)) is met. I don't know ahead of time when this condition will be met. I also plot progress along the way.

I can work around it, of course (using `run_mcmc` as you suggested), but I've been using this pattern often in my research, so I thought it might be nice to have that option.

**Comment by dfm** [comment]
I see - so you just track the value of g(X) at each step and you don't need the whole chain?

Did you look at the https://emcee.readthedocs.io/en/stable/tutorials/monitor/ tutorial that I linked? It basically follows the same workflow.

**Comment by carlosgmartin** [comment]
That's correct, I don't need the whole chain. And yes, thank you for the link.

**Comment by dfm** [comment]
Cool - in that case it probably wouldn't be too hard to add support for an interface like that. Perhaps by explicity passing `iterations=None` or `iterations=-1` or something. I'd want to make sure that `store==True` in that case, as well.

If you or anyone else was interested in opening the pull request, I'd be happy to review it!

**Comment by carlosgmartin** [comment]
Do I need to post this on the emcee-users mailing list, or do you want me to open the pull request right away?

**Comment by dfm** [comment]
Since we've already chatted about it here, no need to post to the list.
