### ISSUE TITLE
Issue on page /tutorials/quickstart.html

### ISSUE THREAD

**Issue by haricash** [dfm/emcee#417]
In the line `sampler.run_mcmc(state, 10000)`, the `state` is a tuple, whose 1st element contains the required initial parameters for the `run_mcmc` to function. Being a first time user, I ran into this issue because of my naivety. It would be great if the documentation could be changed so that first time users can seamlessly work through the quick start section.

**Comment by dfm** [comment]
I'm not sure I understand your issue here, that tutorial is an ipynb that is executed from top to bottom - so it definitely runs! What was the missing piece for you?

**Comment by dfm** [comment]
No problem - it's not that it needs to be run in a notebook. I was just saying that if you run the code in the order that it's listed, it will work, in a notebook or otherwise! I expect that you're either missing a step somewhere when running from the command line, or perhaps you have a version mismatch (line 190 of `ensemble.py` in the most recent version of emcee, would not throw that error...).
