### ISSUE TITLE
Progress bar

### ISSUE THREAD

**Issue by mtagliazucchi** [dfm/emcee#468]
**General information:**

- emcee version: 3.1.4
- platform: Rocky Linux 8.6
- installation method (pip/conda/source/other?): pip

**Problem description:**

I'm running `emcee` on a cluster using `MPI`. I use the option `progress = True`, but its output goes to in the .err file instead of the .out file. How can I fix it?

### Expected behavior:

The output of the progress bar goes to the .out file.

### Actual behavior:

The output of the progress bar goes to the .err file.

**Comment by dfm** [comment]
Thanks for asking - this is the expected behavior! The progress bar is rendered to stderr by design. This progress bar is generated using [tqdm](https://github.com/tqdm/tqdm), and you can pass arbitrary arguments to the `tqdm.tqdm` constructor ([ref](https://github.com/dfm/emcee/blob/f32a8fbea3d22d0b9e988e8f57ec8a7e737f0c01/src/emcee/pbar.py#L53)) using the [`progress_kwargs` argument to `sample` or `run_mcmc`](https://emcee.readthedocs.io/en/stable/user/sampler/#emcee.EnsembleSampler.sample), so you may be able to have `tqdm` write to stdout if that's a behavior that you'd want, but I don't expect to support that out of the box in emcee.
