### ISSUE TITLE
Issue on page /index.html

### ISSUE THREAD

**Issue by ddurnfor** [dfm/emcee#474]
Version 3.1.4 of emcee, when used with the package multiprocessing, seems to take up as much CPU resources as possible regardless of how many cores are specified, i.e. on a computer with 32 cores, if the multiprocessing Pool is defined with 8 cores, it will run on 8 cores at 400%. We've tried uninstalling and reinstalling and it doesn't help, and have confirmed that multiprocessing does not behave this way when used without emcee. Thanks

**Comment by dfm** [comment]
This isn't anything emcee-specific, but often happens when you use libraries (e.g. numpy) that are themselves parallelized when computing your model. [The parallelization tutorial](https://emcee.readthedocs.io/en/stable/tutorials/parallel/) mentions this briefly at the top, and I can't give you much more advice!
